# Generated by Django 2.0.7 on 2018-07-15 07:08

import json
from django.db import migrations, transaction
from django.contrib.gis.db import models


def load_pattern_data(apps, schema_editor):
    Route = apps.get_model('rom', 'Route')
    Pattern = apps.get_model('rom', 'Pattern')

    with open('rom/fixtures/pattern_data.json') as json_file:
        data = json.load(json_file)

        for d in data:
            try:
                with transaction.atomic():
                    route = Route.objects.get(route_onestop_id = d["route_onestop_id"])
                    pattern = Pattern(
                        route = route,
                        pattern_onestop_id = d["pattern_onestop_id"],
                        wk_trips = d["wk_trips"],
                        sa_trips = d["sa_trips"],
                        su_trips = d["su_trips"],
                        wk_00_03 = d["wk_00-03"],
                        wk_03_06 = d["wk_03-06"],
                        wk_06_09 = d["wk_06-09"],
                        wk_09_12 = d["wk_09-12"],
                        wk_12_15 = d["wk_12-15"],
                        wk_15_18 = d["wk_15-18"],
                        wk_18_21 = d["wk_18-21"],
                        wk_21_24 = d["wk_21-24"],
                        wk_24_28 = d["wk_24-28"]
                    )
                    pattern.save()
            except Exception as e:
                print("%s" %e)
                pass

class Migration(migrations.Migration):

    dependencies = [
        ('rom', '0011_pattern'),
    ]

    operations = [
        migrations.RunPython(load_pattern_data)
    ]
